.gitignore, src/cmd/barrierc/MSWindowsClientTaskBarReceiver.h, src/cmd/barrierd/barrierd.cpp, src/cmd/barriers/MSWindowsServerTaskBarReceiver.h, src/lib/common/win32/encoding_utilities.cpp, src/lib/common/win32/winapi.h, src/lib/net/SecureUtils.cpp, src/lib/platform/MSWindowsScreen.cpp, src/lib/server/Config.cpp
Fixed all compiler warnings when building only the command line programs with Windows with Visual Studio 2022 (VC 14.30):
```
"BARRIER_BUILD_GUI": false,
"BARRIER_BUILD_INSTALLER": false
```
I'm quite sure the added numeric type casts are safe with regards to overflow.
The most controversial change is probably the added header `src/lib/common/win32/winapi.h` for just including `Windows.h` - but with preprocessor directives: `WIN32_LEAN_AND_MEAN`, `STRICT` and `NOMINMAX`. Don't know if you think this is a good idea? (And if you have a better name for it...) Main reason is I needed the `NOMINMAX` to avoid conflict with legacy max macro when using `numeric_limits<int>::max()`. There was (and still is outside of the command line "world" I am compiling atm) quite a few instances of the …
=> Windows build warnings

azure-pipelines.yml
Azure will drop support for Mojave builds soon and builds are failing due to agent provisioning issues already.
=> azure-pipelines: Disable macOS mojave build

src/lib/net/SecureSocket.cpp, src/lib/net/SecureSocket.h
Fixed missing free of SSL certificate and combining two similar certifcation check functions into one.
I noticed the existing function `verify_cert_fingerprint` called `SSL_get_peer_certificate` without a following `X509_free`. That surely must lead to a resource leak? Also the existing code called helper function `verify_cert_fingerprint` before `ensure_peer_certificate`, but if the peer has no cert (cert is NULL) then `verify_cert_fingerprint` would return false and the `ensure_peer_certificate` not be called. So the only remaining use of `ensure_peer_certificate` was only when there actually was a certificate, to write a log line with the certificate's subject. Therefore I combined these two into one common function, then only one call to `SSL_get_peer_certificate`, followed by a call …
=> Fixed missing free of SSL certificate

clean_build.sh
This ensures that the all CPU cores are used without introducing any non-portable scripting.
=> clean_build: Use cmake --build . --parallel

clean_build.sh
Unlike make, ninja has sane dependency resolution and this speeds up builds, especially when ccache is used and there are cache matches.
=> Use ninja in clean_build.sh, if available

_config.yml
Seeing as we don't use this file in the project, this commit removes it
to tidy up a bit.
I think we should definitely have a website, but maybe use a separate
repo, with a hook to build with a SSG (GH Actions?), and then publish
the generated files.
At this point of transition though, we should focus on a new release,
and updating all Barrier references to the new project name.
I am not including a newsfragment here, as a website has not been
generated from this file.
=> Remove GH Pages config, we don't use it

clean_build.sh
This quotes the variable `$B_CMAKE_FLAGS` used in the build
initialisation command (CMake). Because we source arbitrary environment
variables earlier on in the script, they could contain whitespace, or
other problematic characters, which might cause some build wonkiness.
=> Quote `$B_CMAKE_FLAGS` variable in build sh script

src/lib/base/NonBlockingStream.cpp
The changed line was supposed to be an assignment to _cntl_previous private member of the class NonBlockingStream. Without this fix, _cntl_previous member never gets any value to be later used in class NonBlockingStream desructor.
* [not needed] I have created a file in the `doc/newsfragments` directory *IF* it is a
=> lib/base: Fix setting original status flags in NonBlockingStream class

clean_build.sh
B_CMAKE_FLAGS may contain multiple options which we want to pass to CMake as separate flags.
Fixes #1450.
This reverts commit f5b4f2ba588dba0ca03467c1fc7f75f133527ecf.
No newsfragment needed.
=> Revert "Quote `$B_CMAKE_FLAGS` variable in build sh script"

.github/workflows/builds.yml, clean_build.sh
The OS images provided by Github contain additional package repositories by default. Unfortunately sometimes contacting these repositories fails, so we switch to vanilla Ubuntu containers.
* [not needed] I have created a file in the `doc/newsfragments` directory *IF* it is a
=> github: Switch to containers for CI on Ubuntu

.github/workflows/builds.yml, CMakeLists.txt, azure-pipelines.yml, dist/rpm/barrier.spec.in, res/config.h.in, src/lib/platform/IXWindowsImpl.h, src/lib/platform/XWindowsImpl.cpp, src/lib/platform/XWindowsKeyState.cpp, src/lib/platform/XWindowsKeyState.h, src/lib/platform/XWindowsScreen.cpp, src/lib/platform/XWindowsScreen.h, src/lib/platform/XWindowsScreenSaver.cpp, src/test/integtests/platform/XWindowsKeyStateTests.cpp
Not sure this counts as "user-visible change" since most users definitely won't see this and most builders either :smile: 
This cleanup vastly simplifies the X11 package checks by using pkgconfig instead. I think at this point we can expect this to exist and work on every system from the last decade. automake and meson are exclusively requiring it, so not using it just makes our life harder.
Plus, most of the checks here were borderline pointless a decade ago, they certainly are now. There are no X servers anymore that don't support XKB/XI2/Xrandr for example, and virtually all desktop systems have all libX* installed anyway.
=> A little bit of CMake cleanup

README.md
`synergy` → `Synergy` and `OS X` to `macOS`
=> Two minor readme fixes

src/lib/net/SocketMultiplexer.cpp, src/lib/net/SocketMultiplexer.h
Also makes `barrierc` respond to SIGINT again which is a rather nice (developer) UX :)
Fixes #1490
cc @ofourdan
=> Fix the hanging integrity tests

.github/workflows/builds.yml, clean_build.sh
Let's rely on cmake just using the native tool's job count
=> Drop forced parallel job count in clean_build.sh

src/gui/src/main.cpp
99% of the time this fails it's because DISPLAY is unset. Some cases
have it set but not point to the X server but that's niche enough we
probably don't need to worry about.
Fixes barrier issue 1735
=> gui: change an error message to something easier to google for

doc/barrierc.1, doc/barriers.1, doc/newsfragments/xinitthreads.removal, src/lib/inputleap/ArgParser.cpp, src/lib/inputleap/ArgsBase.cpp, src/lib/inputleap/ClientApp.cpp, src/lib/inputleap/ServerApp.cpp, src/lib/platform/XWindowsScreen.cpp, src/lib/platform/XWindowsScreen.h, src/test/integtests/platform/XWindowsScreenTests.cpp
This was added 11 years ago but without information in the commit as to
why it was added. Likely there was a bug in some Xlib version that
required this.
This bug was probably fixed a long time ago and as of libX11 1.8
libX11 now always calls XInitThreads anyway. So let's
drop this code.
=> Drop support for --no-xinitthreads

src/lib/inputleap/ArgsBase.h
Missing from 7b85e30c, must have gotten lost during a rebase.
Original PR: #1503
=> Drop a leftover mention of the xinitthreads

src/lib/inputleap/ClientApp.cpp, src/lib/inputleap/ServerApp.cpp
A lot easier to read this way, doubly so if we have multiple winapi
targets in the future.
=> lib: handle the --help winapi arguments with inline ifdefs

.github/workflows/builds.yml
=> Only warn if artifact can't be uploaded, don't fail

CMakeLists.txt
In #1517, I was pointed to a bug on Windows-based systems, where the `vcruntime140_1d.dll` is missing on systems without Visual Studio C++ debug runtimes installed. This means an DLL dependency exception occurs, and users of Input Leap without this DLL, cannot run the program.
This commit makes CMake build Input Leap on Windows using different flags to ensure that IL can build without the debug runtime, but still being debuggable.
=> Adjust builds to run on systems without specific runtime

.github/workflows/builds.yml, .github/workflows/dist.yml
Our "build.yml" workflow isn't CI, it's just a set of build tests. And the "distribution builds" can be mistaken for official ones, so let's rename that too.
Related to #1522
=> CI: rename the workflows to something less generic

doc/newsfragments/fix-crash-when-switching-screens.bugfix, src/lib/platform/XWindowsScreen.cpp, src/lib/platform/XWindowsScreen.h
This code triggers an assertion in gcc's std_vector.h on my system due to a logical button 0 causing a write to m_buttons[-1], and a SIGABRT.
I've tried to make this code do what it seems to be intended to do, but m_buttons isn't actually read from anywhere anyway.
(Maintainer's note (@shymega): PR from debauchee/barrier#1827) (cherry picked from commit 4cc700c363f083c87992ba318d97d74ecbf1e711)
=> Fix out-of-bounds access in XWindowsScreen::updateButtons

CMakeLists.txt
This PR cherry-picks a commit by @whot from https://github.com/input-leap/input-leap/pull/1524.
-----
This commit is prep work for adding a second backend other than X11 on Unix. It makes the X11 build conditional on X11-specific variables instead of just UNIX.
Note that this doesn't actually make the build conditional since we fail if it isn't enabled. But it puts the right pieces in place for future extending.
=> cmake: make X11 builds on unix conditional

src/lib/inputleap/ArgParser.cpp, src/lib/inputleap/ArgParser.h
his PR cherry-picks a commit by @whot from https://github.com/input-leap/input-leap/pull/1524.
-----
This requires us switching from a std::queue to the std::deque (which was used in std::queue as backend container anyway).
=> inputleap: add Argv.contains() to search for an argument

doc/newsfragments/reproducible-build.bugfix, src/gui/src/AboutDialog.cpp, src/gui/src/AboutDialogBase.ui
Build date is a thing that does not useful. It is enough to know the revision which is already supplied via INPUTLEAP_REVISION.
=> gui: Make build reproducible by removing use of __DATE__

doc/newsfragments/ipc-shutdown-crash.bugfix, src/lib/ipc/IpcServer.cpp
m_socket is first deleted and then removed from the handler list. It should be the other way round.
=> ipc: Fix race condition in IpcServer shutdown

src/gui/src/QBarrierApplication.cpp, src/gui/src/QBarrierApplication.h, src/gui/src/ZeroconfBrowser.cpp, src/gui/src/ZeroconfBrowser.h, src/gui/src/ZeroconfRegister.cpp, src/gui/src/ZeroconfRegister.h, src/gui/src/ZeroconfService.cpp, src/gui/src/ZeroconfService.h, src/lib/base/EventQueue.cpp, src/lib/base/EventQueue.h, src/lib/base/NonBlockingStream.cpp, src/lib/base/NonBlockingStream.h, src/lib/base/UniquePtrContainer.h, src/lib/ipc/IpcClient.cpp, src/lib/ipc/IpcClient.h, src/lib/ipc/IpcClientProxy.cpp, src/lib/ipc/IpcClientProxy.h, src/lib/ipc/IpcServer.cpp, src/lib/ipc/IpcServer.h, src/lib/net/IListenSocket.h, src/lib/net/SecureListenSocket.cpp, src/lib/net/SecureListenSocket.h, src/lib/net/TCPListenSocket.cpp, src/lib/net/TCPListenSocket.h, src/lib/server/ClientListener.cpp, src/lib/server/ClientListener.h
This PR is partial cleanup of new/delete pairs where std::unique_ptr can be used to ensure that the stored pointer is deleted.
=> Use std::unique_ptr where possible instead of manual pointer handling

LICENSE, src/cmd/barrierc/barrierc.rc, src/cmd/barrierd/barrierd.rc, src/cmd/barriers/barriers.rc, src/gui/gui.ts, src/gui/res/lang/gui_hu.ts, src/gui/res/lang/gui_ja-JP.ts, src/gui/res/lang/gui_zh-CN.ts, src/gui/res/win/Barrier.rc, src/gui/src/AboutDialogBase.ui, src/gui/src/LogWindow.cpp, src/gui/src/LogWindow.h, src/gui/src/ShutdownCh.h, src/gui/src/main.cpp, src/lib/base/NonBlockingStream.cpp, src/lib/base/NonBlockingStream.h, src/lib/common/DataDirectories.h, src/lib/common/DataDirectories_static.cpp, src/lib/common/Version.cpp, src/lib/common/unix/DataDirectories.cpp, src/lib/common/win32/DataDirectories.cpp, src/lib/platform/MSWindowsDesks.cpp, src/lib/platform/MSWindowsDesks.h, src/lib/platform/MSWindowsHook.cpp, src/lib/platform/MSWindowsHook.h, src/lib/platform/MSWindowsScreen.cpp, src/lib/platform/MSWindowsScreen.h, src/lib/platform/synwinhk.h
This PR reverts some past changes that adjusted copyright notices. InputLeap copyright notices have been added to some important files where missing.
I think that this should clear any pending issues with regard copyright information.
cc @shymega
=> Cleanup copyright information

src/lib/arch/XArch.h, src/lib/arch/unix/ArchDaemonUnix.cpp, src/lib/arch/unix/ArchNetworkBSD.cpp, src/lib/arch/unix/XArchUnix.cpp, src/lib/arch/unix/XArchUnix.h, src/lib/arch/win32/ArchDaemonWindows.cpp, src/lib/arch/win32/ArchNetworkWinsock.cpp, src/lib/arch/win32/ArchSystemWindows.cpp, src/lib/arch/win32/XArchWindows.cpp, src/lib/arch/win32/XArchWindows.h, src/lib/inputleap/win32/AppUtilWindows.cpp, src/lib/inputleap/win32/DaemonApp.cpp, src/lib/ipc/IpcLogOutputter.cpp, src/lib/platform/MSWindowsSession.cpp, src/lib/platform/MSWindowsWatchdog.cpp, src/lib/platform/OSXScreen.mm, src/lib/platform/XWindowsScreen.cpp
The error handling is more complex than necessary. There's lazy error code to string converter that's completely unused. Removing this opens the possibility for removing the XArch base exception class.
=> Cleanup error handling

src/lib/server/Server.cpp
This PR cherry-picks a commit by @ofourdan from https://github.com/input-leap/input-leap/pull/1524.
------
Server::onClipboardChanged() tries to get the clipboard from the sender by calling getClipboard().
getClipboard() however may fail, and return false in that case, yet onClipboardChanged() does not actually check the return value and tries to use the clipboard.
If getClipboard() does nothing as with the EiScreen implementation, bad things can happen, such as an abort of Input Leap on an assertion failure in the marshall() call that follows.
To avoid that annoyance, check the return value from getClipboard() and bail out early (and gracefully) when it's reported as false.
=> lib/clipboard: Do not try to use clipboard if it failed

doc/newsfragments/debugger-app-shutdown.bugfix, src/lib/arch/unix/ArchMultithreadPosix.cpp
The accepted convention to interrupt program that gdb is attached to is by calling Ctrl+C in gdb console. This sends SIGINT which is then intercepted by gdb. However, signals in InputLeap apps are intercepted by sigwait(). This does not allow gdb to intercept them first. As a result, interrupting app via Ctrl+C causes the program to terminate as it thinks it received SIGINT.
This is worked around by checking if app is under debugger and raising SIGTRAP instead if that's the case.
=> lib: Don't shutdown app when debugger interrupts it

.github/workflows/builds.yml
This currently has a breakage, and fails to update, causing the workflow to ultimately fail, and not provide feedback on macOS builds.
This commit removes `brew update`, in an effort to fix CI checks.
=> CI: Remove `brew update` from macOS builds

.github/workflows/builds.yml
This PR  adds a commit that fixes intermittent GH Actions upload errors, that so far is only happening on Windows-based runners.
It replaces #1568.
=> Fix intermittent GH Actions upload errors on Windows.

.github/workflows/builds.yml, CMakeLists.txt
CMake 3.12 has been released on July 2018, more than 4 years ago.
Ubuntu 18:04 LTS includes CMake 3.10 and building on it will require up to date CMake from apt.kitware.org
Ubuntu 20.04 LTS already includes CMake 3.16.
Debian 9 includes CMake 3.7 and building on it will require newer CMake from Debian backports, which contains 3.16 for amd64 and 3.13 for everything else.
Debian 10 (released July 2019) already includes CMake 3.13.
Fedora does not support any release older than 13 months.
RHEL 7 and derivatives will need compiling cmake from source. However the bump to 3.12 does not affect this because it does not contain cmake3 anyway by default.
RHEL 8 or newer and their derivatives contain new enough CMake version in the AppStream repositories.
=> Bump cmake requirement to 3.12

doc/newsfragments/linux-server-preserve-focus.bugfix, src/lib/platform/XWindowsScreen.cpp
> This PR has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/pull/1067
> 
> PR created on: 2021-02-16 by @cryzed
> PR last updated on: 2021-02-16
Fixes #1066.
I'm not sure why this check was here in the first place, but the preserve focus setting should take effect whether the code runs on the server (primary) or the client. This change and a subsequent local build shows that the issue is fixed for me.
=> Fix `Fix Preserve Focus` option not working on Linux servers

doc/newsfragments/memory-leak-during-repeated-reconnections.bugfix, src/lib/base/UniquePtrContainer.h, src/lib/client/Client.cpp, src/lib/client/Client.h, src/lib/inputleap/PacketStreamFilter.cpp, src/lib/inputleap/PacketStreamFilter.h, src/lib/inputleap/ServerApp.cpp, src/lib/io/StreamFilter.cpp, src/lib/io/StreamFilter.h, src/lib/net/ISocketFactory.h, src/lib/net/SecureSocket.cpp, src/lib/net/SecureSocket.h, src/lib/net/TCPSocketFactory.cpp, src/lib/net/TCPSocketFactory.h, src/lib/server/ClientListener.cpp, src/lib/server/ClientListener.h, src/lib/server/ClientProxy.cpp, src/lib/server/ClientProxy.h, src/lib/server/ClientProxy1_6.cpp, src/lib/server/ClientProxy1_6.h, src/lib/server/ClientProxyUnknown.cpp, src/lib/server/ClientProxyUnknown.h, src/test/integtests/net/NetworkTests.cpp
This PR cleans up memory allocations by adding more uses of automatic memory management via std::unique_ptr.
=> Cleanup memory allocations

src/lib/base/EventQueueTimer.h, src/lib/base/IEventQueue.h, src/lib/base/SimpleEventQueueBuffer.cpp, src/lib/platform/MSWindowsEventQueueBuffer.cpp, src/lib/platform/OSXEventQueueBuffer.cpp, src/lib/platform/XWindowsEventQueueBuffer.cpp, src/test/global/TestEventQueue.h
Currently every platform defines its own EventQueueTimer type. This assumes that only one platform can be enabled at a time. In the future this will not necessarily be the case (Ei platform may be enabled together with XWindows). Depending on exact implementation choices this may cause ODR violations.
It's better to expose such an API that extending it in the expected way does not have chance for ODR violations. Having just one EventQueueTimer type is the simpliest solution.
* [not needed] I have created a file in the `doc/newsfragments` directory *IF* it is a
=> lib: Fix potential ODR rule violation due to EventQueueTimer

azure-pipelines.yml
Apparently ninja is not installed on azure pipelines Linux builds, which causes them to finish slower because ninja does not parallelize make builds.
=> azure-pipelines: Install ninja on Linux

src/lib/client/ServerProxy.cpp, src/lib/inputleap/ClipboardChunk.cpp, src/lib/inputleap/ClipboardChunk.h, src/lib/inputleap/FileChunk.cpp, src/lib/inputleap/FileChunk.h, src/lib/server/BaseClientProxy.h, src/lib/server/ClientConnectionByStream.cpp, src/lib/server/ClientConnectionByStream.h, src/lib/server/ClientConnectionLoggingWrapper.cpp, src/lib/server/ClientConnectionLoggingWrapper.h, src/lib/server/ClientProxy.cpp, src/lib/server/ClientProxy.h, src/lib/server/ClientProxy1_6.cpp, src/lib/server/ClientProxy1_6.h, src/lib/server/ClientProxyUnknown.cpp, src/lib/server/IClientConnection.h, src/lib/server/PrimaryClient.h
This interface will allow to mock data connection in the future and more properly test lower level connection bits. Additionally, code is slightly cleaner now because all logging has been moved to yet other wrapper class.
=> Move all server->client message serialization to separate class

clean_build.sh
Forced parallelism has been dropped in commit b477be79e9c. However, it was probably a mistake to do, because not everyone installs ninja by default. Any user who forgets that will get a slow build which is not optimal. Since minimum version of CMake is now 3.12, enabling parallelism is just a single flag.
=> Use --parallel for building in clean_build.sh

src/lib/inputleap/ClientApp.cpp
Since ad7946ec23 all event targets are non-trivial types which depend on the data stored in the target for correct unregistration. This means that the object must still be valid when passing it to EventQueue::remove_handler(), otherwise the behavior is unpredictable.
=> lib: Fix incorrect order of timer destruction

src/lib/base/EventQueue.cpp, src/lib/base/IEventQueueBuffer.h, src/lib/base/SimpleEventQueueBuffer.cpp, src/lib/base/SimpleEventQueueBuffer.h, src/lib/platform/MSWindowsEventQueueBuffer.cpp, src/lib/platform/MSWindowsEventQueueBuffer.h, src/lib/platform/OSXEventQueueBuffer.cpp, src/lib/platform/OSXEventQueueBuffer.h, src/lib/platform/XWindowsEventQueueBuffer.cpp, src/lib/platform/XWindowsEventQueueBuffer.h
In the current implementation timers are not platform-specific. On all currently supported platforms timer costrution and destruction is simple new and delete, so it does not make sense having this customization point.
=> base: Remove IEventQueueBuffor newTimer and deleteTimer APIs

src/lib/base/String.h, src/lib/net/FingerprintData.h
=> Add missing #include directives for gcc13

.github/workflows/builds.yml
For example, the libei builds currently fail, but prevent other Ubuntu jobs from running. This commit will allow them to run.
=> This commit makes the Matrix strategy continue running even on failure

.github/workflows/builds.yml
This should fix builds where cloning from Git mainline, causes a breakage in CI from a breaking change in libei 0.4.
=> CI (libei): Lock clone of libei to 0.3 tag

src/lib/platform/XWindowsScreen.cpp
Some distributions use the scroll lock mask to indicate that an alternate keyboard layout is in use, and this causes hotkeys to not get properly identified when in client screens.
No user visible change
This fixes #1528 
=> Ignore scroll lock mask for hotkey detection

.github/workflows/builds.yml
It was mentioned that libei *does* work with Input Leap on libei (0.4.1), but not from mainline.
So, in the interests of keeping things up-to-date, I'm bumping the clone tag to 0.4.1.
=> Bump libei version from 0.3 to 0.4.1

CMakeLists.txt, src/gui/src/NewScreenWidget.cpp, src/gui/src/Screen.cpp, src/gui/src/ScreenSetupModel.cpp, src/gui/src/ServerConfig.cpp, src/lib/base/UniquePtrContainer.h, src/lib/net/SecureUtils.cpp, src/lib/net/TCPSocketFactory.cpp, src/lib/platform/EiKeyState.cpp, src/lib/platform/EiScreen.cpp, src/lib/platform/PortalRemoteDesktop.cpp, src/lib/platform/PortalRemoteDesktop.h
user-visible change (and make sure to read the `README.md` in that directory) 
----
These are code improvements only, mostly upgrading from deprecated code, so no user-visible change.
1. 4628a7c8b98064f58a5f4dc64cc5680adb12e68a fixes building against the last libportal release (currently CI builds against master, which has caused issues when done with libei)
2. 3557fb55297b011c51fc42a9174a3f880d5d6523 fixes building against the latest libei (i.e. master), which will inevitably be needed at some point
3. 0497e17ba9b18e0cf941733ae56281bdc7fd15a3 is a bug fix, a return statement was missing
4. 6edd9363ac4444b2305585af568e30333b8a46bf a5ff6ced6b797340287cf39aedbd0e10d22696be b4cb8339d4712627f92b53b663b5aad35cb584f4 are 3 different Qt deprecations. Useful to start fixing code before upgrading …
=> Build fixes

res/input-leap.appdata.xml.in
According to our packaging policy (https://docs.fedoraproject.org/en-US/packaging-guidelines/AppData/) AppData files must correctly validate using appstream-util validate-relax.
=> AppData validation fix

src/lib/platform/XWindowsScreen.h
This error was detected upon compiling with `clang++`, and happened with
the `XWindowsScreen` class, where a `virtual` method was missing the
`override` keyword.
This commit fixes the compilation warning.
Error from `clang++`:
```
[138/252] Building CXX object src/lib/platform/CMakeFiles/platform.dir/XWindowsScreen.cpp.o
In file included from /home/dzr/git.shymega.org.uk/input-leap/input-leap/src/lib/platform/XWindowsScreen.cpp:19:
/home/dzr/git.shymega.org.uk/input-leap/input-leap/src/./lib/platform/XWindowsScreen.h:91:18: warning: 'handle_system_event' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
virtual void handle_system_event(const Event& event);
^
/home/dzr/git.shymega.org.uk/input-leap/input-leap/src/./lib/inputleap/IPlatformScreen.h:177 …
```
=> Fix clang++ warning with missing override keyword

src/lib/inputleap/ArgParser.cpp, src/lib/platform/EiKeyState.cpp, src/lib/platform/EiScreen.cpp, src/lib/platform/PortalRemoteDesktop.cpp, src/test/unittests/inputleap/ArgParserTests.cpp
This commit replaces the remaining `NULL` values in the codebase with `nullptr`, in line with C++ recommendations.
=> Replace remaining `NULL` values to `nullptr` instead

src/lib/platform/OSXKeyState.cpp, src/lib/platform/OSXKeyState.h, src/lib/platform/OSXScreen.mm, src/lib/platform/OSXUchrKeyResource.cpp
Notes:
* Tested with FreeBSD server & macOS client
* Function `handleModifierKeys()` is untested; I was unable to trigger a breakpoint in it. Maybe it's only hit when running a server?
There's still something a bit off in the logic when handling multiple simultaneous modifier key presses: Pressing Alt_R-Shift_L works, but pressing Shift_L-Alt_R causes latter to get interpreted with incorrect keycode. I'm not sure if I have time/energy left to address it, but I'll try.
Edit: This seems to be an unrelated XWindow server side issue.
Edit2: It's not a bug, just what happens when shift modifier is applied to alt_r with my current configuration
=> macOS: add support for right side modifier keys

doc/newsfragments/1636_fix_hang_on_macos_suspend.bugfix, src/lib/base/EventQueue.cpp
This PR fix a dead lock that `EventQueue::deleteTimer` may lock its `mutex_` twice.
On my macOS 13, `input-leaps` always hangs if I close the lid when a ubuntu client is connected, and after some tries I found this bug. The 2nd `lock_guard` constructed during `delete timer` will enter a dead loop, making the whole process hang until a `kill -9` command.
This PR ensures the `mutex_` has been released before `delete timer`, so the bug disappears. Maybe a `recursive_mutex` will work better, but this PR is also enough.
=> [fix] fix server hangs on mac suspend

README.md
Makes it easier for an end-user to find the documentation for Input Leap
In the past I wasted a good 20 minutes trying to find detailed documentation for input leap/barrier inside the repository. A note in the readme would have helped me find the documentation in the wiki much sooner (usually I ignore wikis on GitHub because they're often very sparse).
By the way thanks for forking and carrying on the mantle of Synergy/Barrier! I'm really excited to follow along with this project.
=> Add link to wiki in readme

.github/workflows/builds.yml, CMakeLists.txt, src/lib/platform/EiScreen.cpp
libei has a libei-1.0 pkconfig file now, so let's update to that. The rest of the APIs are fairly straightforward renames with the exception of the new BUTTON and SCROLL capabilities (previously part of POINTER/POINTER_ABSOLUTE).
Technically it's possible for an EIS implementation to create a pointer device without buttons or scroll but those wouldn't work well with our implementation so let's just ignore those and require button + scroll.
=> ei: adjust to API changes in libei 1.0.0rc1

src/lib/server/ClientListener.cpp
This caused a null-pointer dereference in EventQueue::remove_handler since that was unconditionally called even when the client was NULL.
=> base: only remove handlers if we actually have a client

src/lib/platform/OSXScreen.mm
@shymega's note: from debauchee/barrier#1927, thank you @junbujianwpl.
I'm creating PRs from Barrier's unmerged PRs for Input Leap. This is so we can a) let the community know that there is an active fork and b) take advantage of the code contributions that Barrier simply isn't accepting. This gives us the benefit of improved codebase and bug fixes, such as this one, which happens on Mac machines.
=> fix: wake up on mac when screen locked

src/lib/platform/PortalInputCapture.cpp, src/lib/platform/PortalRemoteDesktop.cpp
Last minute change before the libportal branch got merged into upstream - it takes a GError instead of returning a negative errno.
And the same change for the inputcapture invocation though that one hasn't been merged yet.
=> ei: xdp_session_connect_to_eis() now takes a GError

src/gui/src/main.cpp
This is a note we can refer back to when Wayland support is stabilised, and we can fully promote Input Leap as 'Wayland-ready'.
By 'stabilised', I mean, works without crashes, works on GNOME/KDE/wlroots/other major DEs/WMs, and users have reported success.
=> Add note to 'Wayland' warning code

src/client/CMakeLists.txt, src/client/input-leapc.exe.manifest, src/server/CMakeLists.txt, src/server/input-leaps.exe.manifest
Seems like a long time ago when this was named Barrier these files got removed here:
https://github.com/input-leap/input-leap/commit/aea488167af19845369e062bf9af4edfadc4fa71
Adding them back into the Windows build seems to correct the issues people have been having moving the mouse away from Windows servers that have their DPI scaling set to anything other than 100%. Should fix these Github issues:
- https://github.com/debauchee/barrier/issues/1713
- https://github.com/input-leap/input-leap/issues/1108
=> Re-add manifests for Windows with DPI-aware flag

doc/newsfragments/1640_revert-1434.bugfix, src/lib/server/Server.cpp
This reverts #1433.
Based on discussion in #1624 it seems like this would be better denoted as intended behavior and if a truly shared clipboard was not desired, that clipboard sharing should be disabled.
Blocking off-screen updates truly is a complex process and there are other parts of the stack that need to be fixed as well (see aforementioned issue). If this is a feature that is desired, a larger update will be needed, and likely should also be introduced as an optional feature.
=> Revert #1433 (blocking off-screen clipboard updates)

doc/newsfragments/1541-fix-broken-tilde-and-grave, src/lib/platform/OSXKeyState.cpp
Fix broken Tilde and Grave (Backtick/Backquote)
This was copied from https://github.com/debauchee/barrier/pull/1711 by
@dgentry.
Resolves #1541 and #1407.
=> Fix missing tilde

doc/newsfragments/README.md, doc/newsfragments/newsfragments-readme-grammar-update.doc
(Ported to Input Leap by @shymega, squashed two duplicate commits, rebased against master.
See: debauchee/barrier#1937)
=> Minor grammatical updates to newsfragments README

src/lib/platform/PortalInputCapture.cpp
Since 5 days ago since CI last ran on master, with commit [whot/libportal#6ecf17f](https://github.com/whot/libportal/tree/6ecf17f1dc99353b470d5cb9fb6e50566e275375) (taken from CI log)  the [`wip/inputcapture`](https://github.com/whot/libportal/tree/7371f619176dc8c7d2ecdfdc1988ee1ce8f1beb7) has been rebased on the lastest main which includes the `0.7.1` release and separation between qt5/qt6:
```
> git show-branch 6ecf17f wip/inputcapture main 
! [6ecf17f] Implement support for the InputCapture portal
* [wip/inputcapture] Implement support for the InputCapture portal
! [main] Introduce libportal-qt6
---
*  [wip/inputcapture] Implement support for the InputCapture portal
*  [wip/inputcapture^] session: implement a generic close/closed handling
*  [wip/inputcapture~2] Move the generic …
```
=> Update for libportal wip/inputcapture rebased on 0.7.1

src/lib/platform/EiScreen.cpp
Update `EiScreen.cpp` usage of `NULL` in method call to `nullptr`, as per C++ style conventions.
=> fix(EiScreen): Change `NULL` to C++ `nullptr`

src/lib/platform/OSXScreen.h, src/lib/platform/OSXScreen.mm
Create a single power management assertion ID for announcing user activity on screen enter, instead of creating a new one each time.
=> macOS: fix power management assertion handling

doc/newsfragments/1644_fix_label_clipboard_max_size.bugfix, src/gui/src/ServerConfigDialogBase.ui
=> Fix cut off label for clipboard max size on GUI Server window

cmake/Version.cmake, src/gui/CMakeLists.txt
Remove duplicate call to `cmake_minimum_version`. 
It should be set only by the main `CMakeLists.txt`.
=> Remove `cmake_minimium_version` declarations from non-root `CMakeLists.txt`

src/CMakeLists.txt
Remove dependency on gtest if tests are disabled (INPUTLEAP_BUILD_TESTS set to OFF)
=> do not require gtest dependency if building without tests

doc/newsfragments/1789_fix_clipboard_sharing_toggle.bugfix, src/gui/src/ServerConfig.cpp, src/gui/src/ServerConfigDialog.cpp, src/gui/src/ServerConfigDialog.h
Fixed clipboard sharing toggle in GUI (https://github.com/input-leap/input-leap/issues/1789)
1. Do not turn on clipboard sharing if clipboard sharing is unchecked, even if the clipboard size limit is above 0
2. Save clipboard size limit to generated server configuration file
3. Enable clipboard size spinbox based on clipboard sharing checkbox
=> Fix clipboard sharing settings in GUI

doc/newsfragments/server-config-dialog-starting-tab-screen.bugfix, src/gui/src/ServerConfigDialogBase.ui
Set initial tab to 0 on ServerConfigDialog window
Change the Server Configuration Dialog, so it opens with the Screens
tab, as opposed to the Advanced tab.
=> Set initial tab to 0 on ServerConfigDialog window

doc/newsfragments/159-fix-corner-size-value.bugfix, src/gui/src/ServerConfigDialogBase.ui
Fixes #159
- Increases the max corner size to 9999.
=> Increase the max corner size to 9999

CMakeLists.txt, doc/newsfragments/qt-cmake-select.feature, src/gui/CMakeLists.txt
user-visible change (and make sure to read the `README.md` in that directory) 
Fixes: #1395
Allow the user to select the Qt Version if both Qt5 and Qt6 are installed.
- Set `QT_DEFAULT_MAJOR_VERSION` to 6 to build with Qt6
- Set `QT_DEFAULT_MAJOR_VERSION` to 5 to build with Qt5 ( Default if not set)
Few Changes to the GUI cmakelist
1. Use `QT_DEFAULT_MAJOR_VERSION` to control the version of Qt Required
-  Qt5 Builds Require Qt Version 5.9+
-  Qt6 Builds Require Qt Version 6.2+
2. Use `QT_DEFAULT_MAJOR_VERSION` in place of `Qt#_Found` for tool guards
=> User Selectable Qt Version at Config time

src/gui/src/ActionDialog.cpp, src/gui/src/AddClientDialog.cpp, src/gui/src/CommandProcess.cpp, src/gui/src/DataDownloader.cpp, src/gui/src/IpcClient.cpp, src/gui/src/IpcReader.cpp, src/gui/src/KeySequenceWidget.cpp, src/gui/src/MainWindow.cpp, src/gui/src/QInputLeapApplication.cpp, src/gui/src/QUtility.cpp, src/gui/src/Screen.cpp, src/gui/src/ScreenSetupView.cpp, src/gui/src/SetupWizard.cpp, src/gui/src/SslCertificate.cpp, src/gui/src/ZeroconfBrowser.cpp, src/gui/src/ZeroconfRegister.cpp, src/gui/src/ZeroconfServer.cpp, src/gui/src/ZeroconfService.cpp, src/gui/src/ZeroconfThread.cpp, src/gui/src/main.cpp
- Use Qt5 style connections 
- Old SIGNAL / SLOT macros are slower and more error prone 
- Use `const &` for current item and a `const list` for input to all ranged for loops to prevent detachment
- Use `Q_EMIT` in place of `emit` emitting a signal (added a few missing ones also )
=> Fix clazy issues

src/lib/platform/PortalInputCapture.cpp
To adhere to the existing unspoken code style in Input Leap, I've
changed the `NULL` argument to `nullptr`.
This isn't a user-visible change, so I didn't create a newsfragment.
<del>* [ ] I have created a file in the `doc/newsfragments` directory *IF* it is a
user-visible change (and make sure to read the `README.md` in that directory)</del>
=> PortalInputCapture: Change `NULL` to `nullptr`

doc/newsfragments/1717_fix-host-freeze-from-logwindow-issue.bugfix, src/gui/src/LogWindow.cpp, src/gui/src/LogWindow.h, src/gui/src/LogWindow.ui
Use a buffer before appending to the log window to significantly lower CPU use Also cap the memory usage by setting maximumBlockCount to 10000. This will purge old log entries from the log window once 10,000 lines have been reached. This caps the memory use around 40 to 50MB
Fixes #1717
v2: based on sithlord48 review
user-visible change (and make sure to read the `README.md` in that directory) 
I took over @hunterzero99 PR #1797  and applied the recommendations from @sithlord48 code review.
One item I recently added is a preprocessor macro to define the logwindow refresh from buffer qtimer timeout.
I also modified the doc fragment file name to include the issue number as the doc for towncrier tells.
The code rationale is hunterzero99. I tested it for more than three days in debug2 log …
=> Buffer the log window entries and cap the memory usage

src/gui/src/ActionDialog.cpp, src/gui/src/ActionDialog.h
When #1837 was split to from #1830 a few non gui changes were left behind , This adds them back
- Remove the need for the ActionDialog to store and have a protected member for the `ServerConfig`.
- Remove the need to track how many items are in the screen combobox to select the current screen 
- Speed up screen list filling (and save some horizontal space) by continuing if the screen is null
- Simplify the logic for the `key_sequence_changed` method
=> gui: ActionDialog A few more logic improvements

.github/workflows/dist.yml
=> github-ci: update to use Fedora 39

CMakeLists.txt, src/lib/platform/EiScreen.cpp, src/lib/platform/EiScreen.h
We may get scroll events or scroll discrete events and both may be in fractions of a single logical scroll event. Handle this by mapping 10 pixels to one wheel click (that's what mutter/gtk do too) and otherwise keeping the remainder around in the device for the next scroll event.
Note that we're always sending things through as wheel, so on the client side we only ever call ei_device_scroll_discrete().
In theory, our pointer and keyboard device may be the same ei device, so let's assume we have a user data on all of them and free them during cleanup - that way we don't need complicated checks of which devices are the same device.
Fixes #1840
cc @brianjmurrell, @prahal
---
Note that there's a remaining issue: mutter seems to be sending both normal and discrete scroll events so the …
=> ei: fix the scroll events

src/lib/platform/PortalInputCapture.cpp
The SESSION_CLOSED signal is on the parent session so we need to disconnect it there too.
../gobject/gsignal.c:2777: instance '0x7fd130001c90' has no handler with id '12'
Fixes f2d7d9f57af218a4ff3762342f361e61021a949d
=> ei: disconnect SESSION_CLOSED from the right session object

.github/workflows/builds.yml
Requires: #1845
- Build a macOS Universal Binary Also build for mac os 12   
- Fixes #1703  
- Fixes #1704 
- Fixes #1057 
- Fixes #960
- Fixes #166 
- Add Os 10.14 Native Arm only on CI 
- Fixes #1208
- CI Updates to support this
-  Build and cache proper openSSL config
- Upload build artifacts for mac os actions.
=> github-ci: Add macOS Universal and Apple Silicon builds

src/gui/src/MainWindow.ui
Set [menuRoles](https://doc.qt.io/qt-6/qaction.html#MenuRole-enum) for the items where possible, this will act as a hint for window managers to put these menu items in the correct location (i.e mac os puts settings under the menu with the app name)
- Configure Settings ->    `PreferencesRole`
- Quit -> `QuitRole`
- About InputLeap -> `AboutRole`
=> gui: MainWindow, Set MenuRoles Where possible

CMakeLists.txt, src/lib/base/EventQueue.cpp, src/lib/base/Log.cpp, src/lib/base/Log.h, src/lib/client/Client.cpp, src/lib/client/ServerProxy.cpp, src/lib/common/common.h, src/lib/inputleap/ClipboardChunk.cpp, src/lib/inputleap/DragInformation.cpp, src/lib/inputleap/DropHelper.cpp, src/lib/inputleap/FileChunk.cpp, src/lib/inputleap/KeyMap.cpp, src/lib/inputleap/PlatformScreenLoggingWrapper.cpp, src/lib/inputleap/StreamChunker.cpp, src/lib/ipc/IpcServer.cpp, src/lib/net/SecureSocket.cpp, src/lib/platform/EiKeyState.cpp, src/lib/platform/EiScreen.cpp, src/lib/platform/OSXClipboard.cpp, src/lib/platform/OSXScreen.mm, src/lib/platform/PortalInputCapture.cpp, src/lib/platform/XWindowsClipboard.cpp, src/lib/platform/XWindowsKeyState.cpp, src/lib/platform/XWindowsScreen.cpp, src/lib/platform/XWindowsScreenSaver.cpp, src/lib/platform/XWindowsUtil.cpp, src/lib/server/ClientConnectionLoggingWrapper.cpp, src/lib/server/ClientProxy1_6.cpp, src/lib/server/Server.cpp, src/test/integtests/ipc/IpcTests.cpp
Wanted to add some log messages for debugging and ended up fixing a whole bunch of annoyances with the log system.
Notably: using `_X_ATTRIBUTE_PRINTF` (stolen from `XFuncproto.h`) and the cmake change means we have `-Wformat` enabled by default now where available which should catch a few errors quickly. I ran into this when I was trying to printf a `std::string` and the compiler didn't tell me.
The last commit simplifies the actual log buffer handling, hopefully to the same result :)
This is on top of #1854 because I didn't want to have to deal with the rebases.
There are some warnings left which are fixed in #1853.
=> Clean up the logging handling

src/lib/platform/EiScreen.cpp, src/lib/platform/EiScreen.h
Fixes #1856
Note that due to the way the logging macros work atm, the resulting file/line numbers will be those from the log handler. #1859 should help with that since we can then directly supply them from the ei context.
=> ei: hook ei logging into our logger

src/lib/platform/EiScreen.cpp, src/lib/platform/EiScreen.h
Add a map that contains the key id and a vector of modifier masks + the assigned hotkey id, then register and lookup those hotkeys as we get the events. This is a bit minimum effort but should get us 80% of the way there, further inspiration can be taken from the X implementation of the same thing.
Note that due to how the InputCapture portal works, this code is not triggered unless we're currently capturing input - and that only happens when we're logically on the remote.
No solution currently exists in the ei backend to capture the key on the server side.
Fixes #1711 (partially)
---
A note here: this is the MVP to get Ctrl+Backspace working and it works in my tests here. The X windows implementation is a lot more complex but I'm running out of time so a mostly-working solution is better …
=> ei: implement server-side hotkey handling

.github/workflows/builds.yml, src/lib/base/EventTypes.h, src/lib/platform/EiKeyState.cpp, src/lib/platform/EiScreen.cpp, src/lib/platform/EiScreen.h, src/lib/platform/PortalRemoteDesktop.cpp, src/lib/platform/PortalRemoteDesktop.h
Use the restore_token provided in RemoteDesktop.Start to re-initialize our sessions if we get disconnected. This gives us back the session without any need for interactive user input after e.g. a lock screen.
Fixes #1699 
cc @prahal
Note: filing this as draft because I haven't fully debugged this yet and there may be some memleaks, this is just the first working version.
Requires:
=> ei: try to restore RemoteDesktop sessions when we lose them

src/gui/src/Action.cpp, src/gui/src/Action.h
Action:
- Use `snake_case_` style names for private vars
- Use arg substitution
- Create a SETTINGS namespace for the settings keys
- Remove redundant switch case
- Remove a pointless Assert 
- Add InputLeap Developers to files copyright
=> gui Code cleaning: Action

src/lib/platform/EiScreen.cpp
getShape() is called as soon as we connect to the server but at this point we do not have a shape yet, we're still waiting for the user to confirm the portal request. If we return all zeroes here the server disconnects us (ClientProxy1_6::recvInfo()), resulting in a continuous connect/disconnect loop until the user finally says yes.
Send an intial screen shape instead, that shape will get updated later when we get the devices through libei.
Fixes #1718
cc @Shuna322, can you give this a try please?
=> ei: start with an initial screen size of 1x1

src/lib/platform/EiScreen.cpp
While this is useful for debugging libei, it's almost never useful for anything else so let's drop the log priority a bit.
=> ei: drop debug priority for ei debug messages

src/gui/src/MainWindow.cpp, src/gui/src/MainWindow.h, src/gui/src/SettingsDialog.cpp, src/gui/src/SettingsDialog.h, src/gui/src/SettingsDialog.ui, src/gui/src/main.cpp
Assorted Code cleanup for the Settings Dialog
- Fixes #1826 : 
- Changes the label to say `Show Tray Icon upon App Start`
- Allow the Checkbox Options to span the columns.
- The dialog will default to 400 width and a height based on the contents
- Remove the auto connections (`on_...`) 
- Make the button box connections in the constructor
- Add InputLeap Developers to the copyright
- Cleanup unneeded includes
- Use Signals to request a language change
- `MainWindow` and `SettingsDialog` are no longer friends
=> gui: code clean up Settings Dialog

src/gui/src/CommandProcess.h, src/gui/src/DataDownloader.h, src/gui/src/IpcClient.h, src/gui/src/IpcReader.h, src/gui/src/KeySequenceWidget.h, src/gui/src/SslCertificate.h, src/gui/src/ZeroconfBrowser.h, src/gui/src/ZeroconfRegister.h, src/gui/src/ZeroconfThread.h
Replace all the `signals` with `Q_SIGNALS` in our Qt using headers
=> Replace signals with Q_SIGNALS

src/gui/src/AboutDialog.cpp, src/gui/src/AboutDialog.h, src/gui/src/AboutDialog.ui
About Dialog
- Add an `Input Leap Developers` line to the copyright of the object files
- Allow it to size itself
- Allow the  the logo scale upto 2x
- Remove unneeded includes 
- Use Arg substitution to create the version string displayed 
- Use `#pragma once`
=> Code cleanup: AboutDialog

src/lib/inputleap/ProtocolUtil.cpp
These are quite noisy and by the time we have errors in the actual protocol mapping we should have ruled out anything above already.
=> lib: drop raw protocol write/read messages to DEBUG5

CMakeLists.txt
Split from #1846 
- Add Configuration option `INPUTLEAP_DEPLOY_FLATPAK_SCRIPT` (default: OFF) to control if the `dist/flatpak/input-leap-flatpak` is installed.
=> Deployment on Linux: Avoid deploying Flatpak file unless in a Flatpak

doc/newsfragments/warn-on-xwayland.feature, src/lib/platform/XWindowsScreen.cpp, src/lib/platform/XWindowsScreen.h
Check if the XWAYLAND extension is available and if so, print a warning. This extension is available in xwayland 23.1.0 and later.
Two comments on the patch:
- the indentation in this file is all over the place with a 50/50 split between tabs and spaces, I stuck with spaces (because `.editorconfig` says so)
- there are heuristics for checking for xwayland (output names, xinput device names) but the extension is the only guaranteed reliable one. It's relatively new but the majority of systems that switch to wayland will also have a relatively new xwayland so I think it's easier to just stick with the simpler call.
=> x11: log a warning if we're running against Xwayland

README.md, doc/newsfragments/1911-builds_note_in_readme.doc
Added a note in `README.md` on how to obtain test builds.
=> `README.md`: Added a note on how to obtain test builds

doc/input-leaps.1, src/lib/common/unix/DataDirectories.cpp, src/lib/inputleap/ServerApp.cpp, src/lib/inputleap/ServerApp.h
Unify `USR_CONFIG_NAME` and `SYS_CONFIG_NAME` into one new `CONFIG_NAME`. This moves the USER based config from `$HOME/.local/share/input-leap/.input-leap.conf` -> `$HOME/.config/Inputleap/input-leap.conf`
Fixes #1851  by correcting the path in the manual.
=> Don't use a hidden file for the config on linux

src/lib/platform/PortalInputCapture.cpp
- KDE doesn't allow the barrier id to be 0, so we need to start from 1. (https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/blob/master/src/inputcapture.cpp?ref_type=heads#L246)
- There is a bug on the bottom barrier that made it never work
=> InputCapture changes for KDE integration

clean_build.sh
`macos_environment.sh` reference in `clean_build.sh` caused a build error.
This fix allows for `macos_environment.sh` to be sourced, if it exists. If not, it doesn't error out.
Related: #1846.
=> fix(macOS): Add check for `macos_environment.sh` in build script

CMakeLists.txt, res/config.h.in, src/lib/platform/PortalRemoteDesktop.cpp
This was added after the 0.7 release which means we have users that have xdp_session_connect_to_eis but not xdp_portal_create_remote_desktop_session_full, causing build errors.
Let's ifdef this out and create a thin wrapper around the older xdp_portal_create_remote_desktop_session which doesn't handle the restore token. This way we get back to the behavior before b3308fc505d3 ("ei: Try to restore RemoteDesktop sessions when we lose them")
Closes #1912
---
Warning: compile-tested only, sorry, I'm seriously ETIME today
=> ei: ifdef out support for remote desktop session restore

src/lib/platform/EiScreen.cpp, src/lib/platform/EiScreen.h
When moving sub low pixels of delta on libei, we should buffer the output so that these small movements are accumulated.
=> libei: Fixed small mouse movements

doc/input-leap.conf.example-advanced, doc/newsfragments/fix-advanced-example.doc
This looks like it was a WIP that got committed a long time ago but never finished, so I've filled out the configuration matching the top comment's setup description to the best of my knowledge.
(See also https://github.com/input-leap/input-leap/discussions/1899)
=> Update `doc/input-leap.conf.example-advanced` to match top comment

.github/workflows/builds.yml
Github no longer has macos-11 runners so we must build x86-64 mac using macos-12
=> Fix x86_64 mac builds

src/gui/src/MainWindow.cpp, src/gui/src/MainWindow.h, src/gui/src/Screen.cpp, src/gui/src/ScreenSetupView.cpp
Guard deprecated Qt methods in Qt6 
- Guard deprecated `QEvent::pos`for Qt6 builds
- Use std::as_const
- fix broken autoconnected method in mainwindow
=> Check for deprecated Qt5 stuff when using Qt6

CMakeLists.txt, cmake/cmake_uninstall.cmake.in, doc/newsfragments/1913-uninstall-target.feature
This works with Make and Ninja.
=> feat: Add support for an 'uninstall' target to CMake

.github/workflows/builds.yml, CMakeLists.txt, dist/flatpak/com.github.input-leap.input-leaps.yml, dist/rpm/input-leap.spec.in, snap/snapcraft.yaml
- Build with Qt6 by default
- Does not change snap or flatpak formulas
=> Make Qt6 the default

.gitignore, clean_build.sh
On Sonoma 14.4.1 I was not able to build without making this change because the SDK path was wrong. xcrun is provided by xcode and gives an exact path to the SDK. This should prevent similar issues in the future.
I also updated the gitignore because I noticed a couple files being generated that don't seem like they should be checked in to git.
=> Update clean_build.sh to use xcrun rather than xcode-select

src/daemon/CMakeLists.txt
- Restore installation of `input-leapd.exe` for windows fixes: #1898
=> build: win32 set install path for input-leapd

.github/workflows/builds.yml, dist/rpm/input-leap.spec.in, src/gui/CMakeLists.txt
Turns out we are not really using anything from the `Qt5Compat` module so it is no longer a dependency.
=> build: Remove unneed Qt5Compat dependency

src/lib/platform/EiEventQueueBuffer.cpp, src/lib/platform/EiKeyState.cpp, src/lib/platform/EiScreen.cpp, src/lib/platform/XWindowsEventQueueBuffer.cpp
A few things picked up during review of https://github.com/symless/synergy/pull/7449
Note that I'm not 100% about the `pipe2()` usage, I guess the CI pipeline will tell us if it's happy with that. Theoretically `pipe2()` requires `_GNU_SOURCE` but something seems to set this already but I can't see where it's coming from.
=> ei: some minor fixes

.github/workflows/builds.yml, .github/workflows/dist.yml
- CI: to use libEi 1.3.0 (ubuntu) 
- CI: Use fedora 40
=> ci: use libei 1.3.0

CMakeLists.txt
Remove `INPUTLEAP_BUILD_INSTALLER` option
This mis named option is on by default and has no reason to be off as it just block the install of support items on linux for any one running `make install` after a build , on mac os it prevents the bundle from being made and one windows seeds wix info. 
We want todo this by default always .. to build a package you call `cmake --build <builddir> --target package` and that will use cpack to build (when the time comes)
=> build: Remove un needed INPUTLEAP_BUILD_INSTALLER option

src/gui/src/MainWindow.cpp
Mac os by default has a menu for APPNAME (with some items auto moved here by the os) so making our menus on mac os  a little differently
Before: 
After:
=> fix: show window and file menu on mac os

src/gui/src/MainWindow.cpp
This fixes GUI build error on FreeBSD/X11:
`src/gui/src/MainWindow.cpp:843:9: error: use of undeclared identifier 'kill'`
I'm not very satisfied with this fix, but I was unable to find any meaningful difference in the build command line for this file on Linux vs. FreeBSD. I don't know how signal.h gets included in the Linux build. Shouldn't be any harm doing it explicitly, anyway.
=> Fix build on FreeBSD

.github/PULL_REQUEST_TEMPLATE.md
User-visible is not entirely clear because it may be interpreted literally (i.e. must change something that user sees). The intended criteria for newsfragment is that any changes affecting end users should have a release note.
Changes that don't affect end users, such as refactors or build system changes do not need release notes.
=> github: Clarify criteria for inclusion of newsfragment

src/lib/inputleap/IPlatformScreen.h, src/lib/inputleap/PlatformScreenLoggingWrapper.cpp, src/lib/inputleap/PlatformScreenLoggingWrapper.h, src/lib/inputleap/Screen.cpp, src/lib/platform/EiScreen.cpp, src/lib/platform/EiScreen.h, src/lib/platform/MSWindowsScreen.cpp, src/lib/platform/MSWindowsScreen.h, src/lib/platform/OSXScreen.h, src/lib/platform/OSXScreen.mm, src/lib/platform/XWindowsScreen.cpp, src/lib/platform/XWindowsScreen.h
Fixes: #1690
Fixes: #1897
This fixes keys being stuck when entering the client 
based on https://github.com/deskflow/deskflow/pull/7520 by @enzious 
This checks to see if we can leave a screen before trying todo so 
Tested ON
=> fix: stuck keys on client

.github/workflows/builds.yml, CMakeLists.txt
Split from #1715 
Bump The required cmake version to 3.21
This is wanted to avoid a possible issue linking OpenSSL 3.0+ in some cases.
=> Require Cmake 3.21

.github/workflows/builds.yml
while waiting for #1804  to land ubuntu updated its cmake version for 22.04 to cmake 3.22. This uses the ubuntu build of cmake instead of the one from the kitware ppa
=> ci: use ubuntu 22.04 version of cmake

.github/workflows/builds.yml, dist/rpm/input-leap.spec.in, res/io.github.input_leap.InputLeap.desktop
Changed the input-leap.spec.in according to https://github.com/input-leap/input-leap/issues/1948
For fedora I looked the package names up with dnf, for suse on https://pkgs.org/.
This will probably not work until https://src.fedoraproject.org/rpms/libportal/pull-request/5 is merged because libportal 0.8 is required.
Some changes are inspired by @Conan-Kudo 's changes in Fedora: https://src.fedoraproject.org/rpms/input-leap/blob/rawhide/f/input-leap.spec
=> Require libei

.github/workflows/builds.yml
Tumbleweed has problems installing dependencies lately (most likely due to glibc upgrade and rebuild). The Docker repository does not provide any specific tags, only latest. As a result, Tumbleweed cannot be depended on for CI builds.
This commit should be reverted as soon as OpenSuse Leap 16 is released or tumbleweed is fixed.
=> github: Remove opensuse/tumbleweed from the build set

src/test/integtests/platform/XWindowsKeyStateTests.cpp, src/test/integtests/platform/XWindowsTestsCommon.h
Sometimes XOpenDisplay simply fails. Since the code is outside the project, there's no other way to work around this except by repeat the call multiple times.
=> test: Improve X11 integtest reliability

doc/newsfragments/config-location-linux.bugfix, doc/release_notes/index.md, src/lib/common/DataDirectoriesCommon.cpp, src/lib/common/unix/DataDirectories.cpp, src/lib/inputleap/ServerApp.cpp
Fixes https://github.com/input-leap/input-leap/pull/1892.
=> Add automatic user config migration from old code path on Linux

.github/workflows/builds.yml, dist/scripts/download_release.py, doc/newsfragments/ubuntu-24-04-build.feature
Extracted from https://github.com/input-leap/input-leap/pull/1988, co-authored by @sithlord48
=> Add build for Ubuntu 24.04

.github/workflows/builds.yml, dist/scripts/download_release.py, doc/newsfragments/ubuntu-20-02-build.removal
Extracted from https://github.com/input-leap/input-leap/pull/1988, co-authored by @sithlord48
=> Remove packages for Ubuntu 20.04

.github/workflows/builds.yml
=> github: Build Debian tests with Wayland support always enabled

src/gui/src/MainWindow.cpp, src/gui/src/ScreenSettingsDialog.cpp
=> Remove leftover Qt5 support code

.github/workflows/builds.yml, dist/debian/rules, dist/scripts/download_release.py, doc/newsfragments/ubuntu-24-10-build.feature, doc/newsfragments/ubuntu-wayland-support.bugfix
This PR fixes release deb packages to correctly enable Wayland
=> Wayland build fixes

doc/newsfragments/screen-name-entry.bugfix, src/gui/src/ScreenSettingsDialog.cpp
Current code was limiting the screen name to single character.
=> gui: Fix screen name entry in screen settings dialog

.github/workflows/builds.yml, dist/scripts/download_release.py
This affects the name of the artifacts. There's a single Windows build, so it's doesn't make sense to include Qt version there.
=> github: Remove Qt6 from Windows workflow name

dist/scripts/download_release.py
Windows Qt5 artifact should have been removed in the Qt5 removal commits.
=> dist/scripts: Remove no longer existing artifact

README.md
A lot of parts in README no longer apply after 3.0 release.
=> README: Update post 3.0 release

README.md
=> README: Remove remaining mention of Wayland not being supported

src/lib/inputleap/Clipboard.cpp, src/lib/inputleap/Clipboard.h, src/lib/inputleap/IClipboard.cpp, src/lib/inputleap/IClipboard.h, src/lib/platform/MSWindowsClipboard.cpp, src/lib/platform/MSWindowsClipboard.h, src/lib/platform/MSWindowsScreen.cpp, src/lib/platform/OSXClipboard.cpp, src/lib/platform/OSXClipboard.h, src/lib/platform/XWindowsClipboard.cpp, src/lib/platform/XWindowsClipboard.h, src/lib/platform/XWindowsScreen.cpp, src/lib/server/Server.cpp, src/test/integtests/platform/MSWindowsClipboardTests.cpp, src/test/integtests/platform/OSXClipboardTests.cpp, src/test/unittests/inputleap/ClipboardTests.cpp
The new name is the accepted standard for what the code does. empty() is usually non-modifying operation, so previous name was confusing.
=> lib: Rename IClipboard::empty() to IClipboard::clear()

src/lib/inputleap/ServerApp.cpp, src/lib/server/Config.cpp, src/lib/server/Config.h, src/lib/server/InputFilter.cpp, src/lib/server/InputFilter.h, src/lib/server/Server.cpp, src/lib/server/Server.h
Classes that store data should do only that exclusively instead of coupling with the rest of application.
=> Cleanup configuration handling

doc/newsfragments/arch_bug_when_configuring_server.bugfix, src/gui/src/ServerConfigDialog.cpp, src/gui/src/ServerConfigDialog.h
Fixed a segmentation fault that would occur when configuring servers on certain platforms. This solution was proposed by sithlord48 and they used it to fix the issue for deskflow.
This should fix #2067
=> fix: Seg fault on arch linux when configuring server. Error with server config dialog show event.

doc/newsfragments/wrong_key_mappings_in_osx_clients.bugfix, src/lib/platform/OSXUchrKeyResource.cpp
Fixed an issue with mapping keys in OSX clients introduced in #1635, where keys like the equals sign "=" or the back tick "`" wouldn't be mapped correctly.
Fixes #1990 
Fixes #2099 
Fixes #2077
=> fix: Wrong key mappings in OSX clients

src/gui/res/mac/Info.plist
Possibly stops application from being terminated early due to memory pressure, which is usually undesired for an app providing mouse/keyboard access.
I tried to create an Issue for this 5 times, but consistently got a 500 back from github.  No idea why.
My InputLeap (and Barrier before it) is sometimes restarting many times in a row on MacOS. I was hoping the upgrade to InputLeap would fix it, but sadly, no.
Logging, even with debug1, only gave me "The process exited normally."
Attaching lldb and breaking on exit, however, gave me this:
```
(lldb) thread backtrace
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.5
* frame #0: 0x0000000182f3e730 libsystem_c.dylib`exit
frame #1: 0x0000000186eb4e34 AppKit`-[NSApplication terminate:] + 2084
frame #2: 0x0000000186eb4540 …
```
=> MacOS: Add NSSupportsSuddenTermination = false to application plist

doc/newsfragments/fixed_utf-16_surrogate_pairs_handling.bugfix, src/lib/base/Unicode.cpp
The data pointer needs to move before decoding the second surrogate, and not after. The first surrogate was begin decoded again, resulting in an invalid codepoint.
This affected clipboard operations originating on Windows machines, where the text is encoded in UTF-16 and copying characters from a high plane (like emojis) was broken.
=> Fixed UTF-16 surrogate pairs handling.

doc/newsfragments/fixed_keymap_loading_fail_on_wayland.bugfix, src/lib/platform/EiKeyState.cpp
On some systems, the keymap file provided by Ei required to create the XKB context is not properly seeked to the start.
This will cause reading the file to fail (or, more accurately, just cause 0 bytes to be read), causing the keymap to just default to a US-keymap.
This PR fixes this, causing the correct keymap to be loaded.
=> Fix keymap not correctly loading for the Ei backend

res/io.github.input_leap.InputLeap.appdata.xml
These changes are required so that the flatpak-builder linter doesnt complain about this files. Ill add the screenshots in a bit.
=> feat: make appstream data compliant with flathub standards

doc/newsfragments/add_reload_action_to_tray_icon.feature, src/gui/src/MainWindow.cpp, src/gui/src/MainWindow.ui
Sometimes the clipboard copy function does not work. In this case, when the input-leap is reloaded, the function works normally again. To make reload easier, add a reload action to the tray icon.
After this patch:
=> Add a reload action to the tray icon menu.

doc/newsfragments/MacOS_cursor_jump_when_entering_bug.bugfix, src/lib/platform/OSXScreen.mm
This was the easiest and probably best solution to #1043 .
=> Fixed MacOS cursor jump, issue 1043

doc/newsfragments/input-capture_fix_disabled_call.bugfix, src/lib/platform/PortalInputCapture.cpp, src/lib/platform/PortalInputCapture.h
The options argument was missing so the argument data wasn't the right one and the method cb_disabled was actually called on a GVariant* instead on a PortalInputCapture*
=> input-capture: Fix disabled call

doc/newsfragments/fixed_ei_screen_shape.bugfix, src/lib/platform/EiScreen.cpp
These values were not reset each time the screen shape was update, so if the screen shrink the values will be invalid and lead to borders not triggered.
Also x and y need to be initialised at they maximum values or else they will be always 0 since only min are called on them in the calculation processs.
=> ei: reset w h x y when calculating screen size

doc/newsfragments/windows_dead_keys.bugfix, src/lib/platform/MSWindowsKeyState.cpp
After getting a dead key from `ToUnicodeEx`, add an additional `VK_SPACE` to the keyboard state so we reset the dead key flag and subsequent calls with modifiers, like shift, return the right result (-1) instead of 1.
This happened because without reseting the dead key status the new one was attempted to be composed with the old one, which failed and the end result was a single unicode codepoint not marked as a dead key.
This opens the door to potentially use the returned unicode from the second call to `ToUnicodeEx` as the key character instead of maintaining the getDeadKey function.
I submitted this change to Synergy and Barrier (https://github.com/debauchee/barrier/pull/1583), but the Barrier PR was never merged.
=> Address issues with modifiers and dead keys on Windows

src/gui/src/KeySequence.cpp
Based off these comments on #2231.
- https://github.com/input-leap/input-leap/pull/2231#issuecomment-2823052026
- https://github.com/input-leap/input-leap/pull/2231#issuecomment-2824062717
And this patch: https://gist.github.com/sid-code/9131300ee943af1ce5958ee40e527b93
Closes: #2231.
Closes: #2221.
=> fix(gui): Adjust KeySequence.cpp for Qt > 6.9 change

README.md
Adds a disclaimer about AltGr key combinations when the server is Linux and the client is Windows, noting that they might not work out of the box. Refers to issue #100 for a workaround.
=> Added prevalent known issue to FAQ section on Readme.md
