input-leap/input-leap

doc/newsfragments/hungarian-translation.bugfix
src/gui/res/lang/gui_hu.ts

This is a port of https://github.com/debauchee/barrier/pull/1458 to input-leap.
Thanks @ViBE-HU.

gui: Update Hungarian translation

---

src/lib/barrier/FileChunk.cpp

This is a port of https://github.com/debauchee/barrier/pull/1471 to InputLeap.
Thanks @unit193.

Fix typo: chunck → chunk.

---

src/lib/arch/IArchString.cpp

This probably made sense historically, but nowadays we have this functionality guaranteed to be present by the C++ standard.
Removal of locking should improve performance in any contended cases.

lib/arch: Use reentrant multibyte conversion functions

---

clean_build.sh

Rename Barrier -> Input Leap in build sh script

---

azure-pipelines/build_env_tmpl.bat
azure-pipelines/download_install_qt.ps1

to match MacOS and Linux. This is the last OSS version of Qt 5.x.

Issue #1441 Update the windows builders to use Qt 5.15.2

---

README.md

Inital update of README - more work to be done

---

.github/workflows/builds.yml

See https://github.com/actions/virtual-environments/issues/5583

github: switch from deprecated macos 10.15 to 12

---

src/lib/arch/unix/ArchMultithreadPosix.cpp
src/lib/base/Event.h
src/lib/base/EventQueue.h
src/lib/base/IEventQueue.h
src/lib/inputleap/ArgsBase.h
src/lib/platform/XWindowsEventQueueBuffer.cpp
src/lib/platform/XWindowsEventQueueBuffer.h
src/lib/platform/XWindowsScreen.h

Some really old commits I had in my barrier branch, copied over to IL now. The files modified for whitespace are just some random ones I looked at. I don't disagree with the new approach without alignment, but IMO this should be done all at once rather than mixing it.
Verify that only whitespace changed with `git diff --ignore-all-space HEAD~`.

A few whitespace fixes

---

.github/workflows/builds.yml
clean_build.sh
src/gui/CMakeLists.txt
src/test/integtests/CMakeLists.txt
src/test/unittests/CMakeLists.txt

github workflow is for the linux builds only atm. And obviously they fail because of #1490, so waiting with this PR until #1494 is merged is best.

Hook up the tests via cmake and in the github workflows

---

.github/workflows/builds.yml
src/lib/base/Unicode.cpp
src/lib/inputleap/ArgsBase.cpp
src/lib/server/Server.cpp
src/test/unittests/inputleap/ArgParserTests.cpp
src/test/unittests/inputleap/GenericArgsParsingTests.cpp

Adding ubuntu 22.04 to the build system mix, the rest is just janitorial

A few minor fixes to the CI

---

azure-pipelines.yml

Enable macOS Monterey builds on Azure Pipelines

---

azure-pipelines.yml

This should speed-up builds significantly

azure-pipelines: Install ninja on macOS

---

src/lib/inputleap/ServerApp.cpp

Clang compatibility 

---

dist/debian/docs
dist/debian/inputleap.examples
dist/debian/inputleap.manpages
dist/debian/rules
dist/debian/source/format

This is applied from @draekko's Gist from issue #1602, which I've turned into a PR.
Thank you!

Fix Debian packaging scripts

---

src/lib/net/SecureUtils.cpp

- On OpenSSL ≥ 3.0 we use the up-to-date code. In versions ≥ 0.9.8 but < 3.0 we get a warning. Unfortunaltely some (CI) platforms still do not have access to OpenSSL ≥ 3.0
- `EVP_PKEY_assign_RSA()` was also deprecated since ≥ 3.0 since it is not needed anymore: EVP_RSA_gen() returns a EVP_PKEY* directly. Remove the EVP_PKEY_assign_RSA() call and use explicit pointers instead of auto to clarify what is going on.
I initially added deprecation ignores for OpenSSL ≥ 0.9.8 < 3.0 but adding the proper code is not that much harder if we need to specifically cater to that series of OpenSSL versions anyway (with warning ignores or other).

Fix further OpenSSL deprecation warnings

---

.github/ISSUE_TEMPLATE/bug_report.yml

feat(issue template): Add helpful advice to template

---

dist/rpm/input-leap.spec.in

This extracts part of https://github.com/input-leap/input-leap/pull/1629 that can go in separately.

Add SUSE spport to input-leap.spec.in

---

src/gui/src/ScreenSetupView.cpp
src/gui/src/ScreenSetupView.h

This addresses a problem that slipped through in https://github.com/input-leap/input-leap/pull/1469.

gui: Port ScreenSetupView::viewOptions to Qt6

---

README.md

After some confusion on the status of Input Leap (#1696), I took the liberity of editing the README to be more accurate.

Clarify README to accurately explain status of project

---

src/lib/platform/PortalInputCapture.cpp

Some fixes to the barrier handling and connection to the right signal

A few minor fixes to the InputCapture backend

---

doc/newsfragments/handle-super-modifier-on-wayland.bugfix
src/lib/platform/EiKeyState.cpp

Handle super modifier in EiKeyState

---

doc/newsfragments/handle-super-modifier-on-wayland.bugfix
src/lib/platform/EiKeyState.cpp

Reverts input-leap/input-leap#1811
Per https://github.com/input-leap/input-leap/issues/1816.

Revert "Handle super modifier in EiKeyState"

---

src/gui/src/ActionDialog.cpp
src/gui/src/ActionDialog.h
src/gui/src/ActionDialog.ui
src/gui/src/KeySequenceWidget.cpp
src/gui/src/KeySequenceWidget.h

This PR ports parts of https://github.com/input-leap/input-leap/pull/1830 that can be merged immediately.

gui: Cleanup action dialog code

---

.github/workflows/builds.yml
.github/workflows/dist.yml

Corrected Version of #1808
Closes #1808

Update GH build actions

---

.gitignore

- Add CMakeLists.txt.user to gitignore

git: gitignore add CMakeLists.txt.user

---

.github/workflows/builds.yml
src/gui/src/MainWindow.cpp
src/gui/src/ZeroconfService.cpp

Switch up builds so windows 2019 runner builds Qt5 and 2022 runner build Qt6

Windows qt6

---

.github/workflows/builds.yml

- Named the linux jobs 
- Enable wayland for both ubuntu 22.04 jobs
- Linux ci jobs will now upload artifacts to the job results.

github-ci: Upload Linux builds

---

.github/PULL_REQUEST_TEMPLATE.md

github: update the pull request template to make it less confusing

---

.github/workflows/builds.yml

- Remove ubuntu-18.04 from the job matrix.
- closes #1849

github-ci: Remove the ubuntu 18.04 builder

---

src/lib/platform/EiScreen.cpp

Two conflicting PRs were merged at the same time.

Fix build error due to logical merge conflict

---

src/lib/platform/EiScreen.cpp
src/lib/platform/EiScreen.h

Three fixes necessary for the ei client/server to work a bit less buggily. 
Third commit fixes #1871

A few ei fixes again

---

.github/workflows/builds.yml

FreeBSD CI build

---

clean_build.bat
clean_build.sh
pre-build.bat

Reverts input-leap/input-leap#1981
This breaks my workflow.

Revert "build: remove stale build scripts"

---

src/lib/arch/win32/ArchMiscWindows.cpp
src/lib/arch/win32/ArchTaskBarWindows.cpp
src/lib/arch/win32/ArchTaskBarWindows.h
src/lib/base/Log.h
src/lib/common/common.h
src/lib/platform/MSWindowsWatchdog.cpp

Turns out that Qt enables permissive build option and a lot of problems are not noticed. This PR fixes a number of them.

Miscellaneous Windows fixes

---

.github/workflows/builds.yml
clean_build.ps1
dist/inno/input-leap.iss.in
dist/inno/scripts/products.pas
dist/inno/scripts/products/vcredist2017.iss

Miscellaneous release-related fixes

Release fixes

---

.github/workflows/builds.yml

github: Build in parallel on FreeBSD

---

.github/workflows/builds.yml

github: Enable unity build

---

RELEASING.md

RELEASING: Simplify release instructions
